spring:
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/llm-db # ????????? URI MongoDB
  ai:
    llm:
      base-url: ${BASE_URL}
      api-key: ${API_KEY}
      model: ${MODEL}
      max-tokens: ${MAX_TOKENS}
      temperature: ${TEMPERATURE}
      top-p: ${TOP_P}
      stream: ${STREAM}



server:
  port: ${PORT}

management:
  endpoints:
    web:
      exposure:
        include: "*"
