spring:
  data:
    mongodb:
      uri: ${MONGO_DB_URI}


  ai:
    llm:
      base-url: ${BASE_URL}
      api-key: ${API_KEY}
      model: ${MODEL}
      max-tokens: ${MAX_TOKENS}
      temperature: ${TEMPERATURE}
      top-p: ${TOP_P}
      stream: ${STREAM}




server:
  port: ${PORT}

management:
  endpoints:
    web:
      exposure:
        include: "*"

feature:
  save-to-mongodb-enabled: true


